# Generated by Django 4.2.1 on 2023-05-06 12:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='workgroup',
            name='lessonDays',
            field=models.JSONField(default=''),
        ),
    ]
