# Generated by Django 4.2.1 on 2023-05-06 12:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_workgroup_lessondays'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='workgroup',
            name='lessonDays',
        ),
    ]
