# Generated by Django 4.2.1 on 2023-05-06 22:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_workgroup_groupdays'),
    ]

    operations = [
        migrations.CreateModel(
            name='WorkDay',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('day', models.CharField(choices=[('ПН', 'Понедельник'), ('ВТ', 'Вторник'), ('СР', 'Среда'), ('ЧТ', 'Четверг'), ('ПТ', 'Пятница'), ('СБ', 'Суббота'), ('ВС', 'Воскресенье')], max_length=10)),
            ],
        ),
        migrations.RemoveField(
            model_name='workgroup',
            name='groupDays',
        ),
        migrations.AddField(
            model_name='workgroup',
            name='groupDays',
            field=models.ManyToManyField(to='core.workday'),
        ),
    ]
