# Generated by Django 4.2.1 on 2023-05-07 09:32

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0007_workgroup_groupstudents_alter_workgroup_groupdays'),
    ]

    operations = [
        migrations.CreateModel(
            name='Department',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('depTitle', models.CharField(max_length=150, unique=True)),
                ('groupPrice', models.IntegerField()),
                ('indPrice', models.IntegerField()),
            ],
        ),
        migrations.AddField(
            model_name='workgroup',
            name='groupDep',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='core.department'),
        ),
    ]
