# Generated by Django 4.2.1 on 2023-05-07 09:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0008_department_workgroup_groupdep'),
    ]

    operations = [
        migrations.AddField(
            model_name='workgroup',
            name='groupType',
            field=models.CharField(choices=[(1, 'Групповые занятия'), (2, 'Индивидуальные занятия')], default=(1, 'Групповые занятия'), max_length=100),
        ),
    ]
