# Generated by Django 4.2.1 on 2023-05-08 12:43

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('core', '0012_workgroup_grouptime'),
    ]

    operations = [
        migrations.AlterField(
            model_name='workgroup',
            name='groupStudents',
            field=models.ManyToManyField(blank=True, related_name='group_students', to=settings.AUTH_USER_MODEL),
        ),
    ]
