# Generated by Django 4.2.1 on 2023-05-09 20:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0013_alter_workgroup_groupstudents'),
    ]

    operations = [
        migrations.CreateModel(
            name='WorkGroupPost',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('postCreationDate', models.DateTimeField(auto_created=True)),
                ('postTag', models.CharField(choices=[('Сообщение', 'Сообщение'), ('Важно', 'Важно')], max_length=100)),
                ('postTitle', models.CharField(max_length=200)),
                ('postBody', models.TextField()),
            ],
        ),
    ]
