# Generated by Django 4.2.1 on 2023-05-06 15:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_remove_workgroup_lessondays'),
        ('accounts', '0004_user_work_groups_alter_user_email_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='work_groups',
            field=models.ManyToManyField(blank=True, related_name='user_groups', to='core.workgroup'),
        ),
    ]
